//Add myself to the database
window.visitor = "ericsonmichaelj";
streams.users.ericsonmichaelj = [];
  window.pageOn = "ericsonmichaelj"

//Function for adding the tweet to the document itself
var newTweet = function(index,$body,tweet){
  var $tweet = $('<div class="tweet"></div>');
  $tweet.html("<a>" + "@"  + tweet.user  +"</a>" + ': ' + "<span class='time'>" +jQuery.timeago(tweet.created_at) + "</span>" +  "<br>" +  tweet.message);
  $tweet.appendTo($body);
};

$(document).ready(function(){
  var $body = $('.tweets');
  //Adding a tweet by myself
  $(".submit_tweet").on('click',function(){
    var $message= $(".tweet-message").val();
    writeTweet($message,$body);
    var index = streams.home.length - 1;
    var tweet = streams.home[index];
    newTweet(index,$body,tweet);
  });
  //Once link is clicked add it as page on
  $(document).on('click',".tweet a",function(){
    var user= $(this).text();
    pageOn = user.slice(1,user.length);
    $(".tweets").empty();
  });
  ///return back to normal once you click home
  $("header li:first-of-type").on('click',function(){
    pageOn = "ericsonmichaelj";
  });

  //Adding a tweet generated by the computer
  setInterval(function(){
    $body.html('');
    var index;
    if (pageOn === 'ericsonmichaelj'){
      index = streams.home.length - 1;
    } else{
      index = streams.users[pageOn].length -1;
    }
    while(index >= 0){
      var tweet;
      if (pageOn === 'ericsonmichaelj'){
         tweet = streams.home[index];
      } else{
        tweet = streams.users[pageOn][index];
      }
      newTweet(index,$body,tweet);
      index -= 1;
    }
  },500);

});
